numeros = {1, 2, 3, 2} # NÃO É POSSÍVEL BUSCA INDEX NO "SET", PARA QUE ISSO SEJA FEITO, ELE TEM QUE SER CONVERTIDO PARA UMA LISTA!

numeros = list(numeros) #CONVERSÃO DO "SET" PARA UMA LISTA

print(numeros)

print(numeros[0]) #imprime = 1
print(numeros[1]) #imprime = 2
print(numeros[2]) #imprime = 3 
print(numeros[-1]) #imprime = 3  O RESULTADO É 3, POIS A O "SET" JA REMOVEU AS DUPLICIDADES, E FOI CONVERTIDO PARA UMA LISTA.

# print(numeros[-1]) = 3 DO "SET" NUMEROS. SEMPRE LEMBRE QUE A ORDEM DENTRO DE UM "SET" NÃO É A MESMA DA ENTRADA, NESSA LINHA, O "NUMEROS[-1]" É 3, PORQUE O 2 NO "SET" INICIAL ERA O NÚMERO DUPLICADO. LOGO DEPOIS DA CONVERSÃO DO "SET" O "NUMERO" QUE FOI CONVERTIDO EM LISTA, AGORA TEM UMA NOVA ORDEM FORA DE ORDEM, POREM NESSE EXEMPLO, FICOU NA ORDEM, MAIS NÃO PODE CONFIAR QUE SEMPRE SERÁ ASSIM.